language: node_js
node_js:
  - "10.12.0"

before_install:
  - npm install

before_script:
    - docker-compose up --build -d
    - sleep 10
    - docker-compose restart liquibase
    - npm test

script:
    - py.test

sudo: required
dist: trusty

services:
  - docker
