language: node_js
node_js:
  - "10.12.0"

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - npm install

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up --build -d
  - sleep 10
  - docker run --rm -v $(pwd)/migrations:/liquibase/ -e "LIQUIBASE_URL=jdbc:postgresql://localhost:5432/honeycomb" -e "LIQUIBASE_USERNAME=honeycomb_user" -e "LIQUIBASE_PASSWORD=iamaninsecurepassword" -e "LIQUIBASE_CHANGELOG=/liquibase/main.yml" --network="host" webdevops/liquibase:postgres update

script:
  - npm test

sudo: required
dist: trusty

services:
  - docker
