language: node_js
node_js:
  - "10.12.0"

env:
  global:
    # GIT_TOKEN 
    - secure: "4E9g0DZ3Sgjp7fnIGHszqk9e96O1BbcnGAZv/ZNElBYW0otyebwwLVp3K1B+1zK7hTBvecDnqwhjpCBkvO45dBEZBJoHmo/6xGR5mVCqn50LjYY4eo3/fSbdSysTq0PvN7ru/o8b4bCI7BCg4uiLAWEYS512lWcW/nDg8/z4CUExHjryrVzndrw6KxygBjyE+ibNQDTjnlB2HZVcacuVd0OSKnlhtNAU1pm3szHRwbl+i9jvqtSqkbT6d+wqonagmx0LgStqHOtqWBLJRoxxHUmOEI+3YyEDDmIAjJBn/oRvtDv56+wH28OE/RXcJyzIlvCpqewkHWsj97ur1HiXxc726luf2DQTctEp17DXPxJ0UDm7hj1CoMbJi4K10FvqF7tju0D/2kxL0Lff1sZGQIjrgSH8jEMQG5Af3w0aXuRIGWwj2ZJIpGF3W8YJYowi3in+eJQIQE0zYYefSyNGYA+5vbapBDLWZKCOQPYo7fNqHKllHMrkQLhHym2oSmzw7nMkh5TAsRDFFm6mrM5UEpbLRiNXACXhcQSssE0awRBxuOP52JlqxI5J/w3roPMauMEKzA4nsFg+P6nzuHmXoqZTNfJBI/w575Ss5gSfL5vBYfAsOkVeDqcj3TjQCN28sBu5dUov0GsUvOs4LnPjkva/vWYLpI8f99ox/YH8ckk="
    - GIT_TAG=v$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER

sudo: required
dist: trusty

services:
  - docker

before_install:
- docker pull postgres:10.4
- sudo service postgresql stop
install:
- npm ci
script:
- npm run coverage

deploy:
  provider: script
  on:
    type: push
  script: bash scripts/tag.sh
