language: node_js
node_js:
  - "10.12.0"

before_install:
  - npm install

before_script:
    - psql -c 'create database honeycomb;' -U postgres
    - docker pull webdevops/liquibase:postgres
    - docker run --rm -v $(pwd)/migrations:/liquibase/ -e "LIQUIBASE_URL=jdbc:postgresql://localhost:5432/honeycomb" -e "LIQUIBASE_USERNAME=postgres" -e "LIQUIBASE_CHANGELOG=/liquibase/main.yml" --network="host" webdevops/liquibase:postgres update

script:
    - py.test

sudo: required
dist: precise

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

services:
  - postgresql
  - docker
