version: '3.6'
services:

  minio:
    image: "minio/minio:latest"
    restart: always
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: myaccesskey
      MINIO_SECRET_KEY: mysecret
    volumes:
      - type: bind
        source: ./minio-data
        target: /data

  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: honeycomb_user
      POSTGRES_DB: honeycomb

  honeycomb-service:
    build:
      context: ./build
      dockerfile: local/Dockerfile
    depends_on:
      - minio
      - postgres
    environment:
      NODE_ENV: docker-compose
      ENV: local
      PGPASSWORD: iamaninsecurepassword
      PGUSER: honeycomb_user
      PGDATABASE: honeycomb
      PGHOST: postgres
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY: myaccesskey
      AWS_SECRET_KEY: mysecret
      S3_MINIO: "true"
    ports:
      - 4000:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ../graphql-beehive/
        target: /app/node_modules/@wildflowerschools/graphql-beehive/
      - type: bind
        source: ../graphql-s3-directive/
        target: /app/node_modules/@wildflowerschools/graphql-s3-directive/
