version: '3.6'
services:

  postgres:
    image: postgres:10.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: honeycomb_user
      POSTGRES_DB: honeycomb


  liquibase:
    image: webdevops/liquibase:postgres
    depends_on:
      - postgres
    environment:
      ENV: local
      LIQUIBASE_PASSWORD: iamaninsecurepassword
      LIQUIBASE_USERNAME: honeycomb_user
      LIQUIBASE_CHANGELOG: /liquibase/main.yml
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/honeycomb
    command: update
    volumes:
      - type: bind
        source: ./migrations
        target: /liquibase


  honeycomb-service:
    build:
      context: ./build
      dockerfile: local/Dockerfile
    depends_on:
      - postgres
    environment:
      ENV: local
      PGPASSWORD: iamaninsecurepassword
      PGUSER: honeycomb_user
      PGDATABASE: honeycomb
      PGHOST: postgres
    ports:
      - 4000:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
