version: '3.6'
services:

  minio:
    image: "minio/minio:latest"
    restart: always
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: myaccesskey
      MINIO_SECRET_KEY: mysecret
    volumes:
      - type: bind
        source: ./minio-data
        target: /data

  postgres:
    # image: wildflowerschools/docker-postgres:10.4-alpine-v5
    # image: postgres:10.4
    build:
      context: ./
      dockerfile: build/local/postgres/Dockerfile
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: honeycomb_user
      POSTGRES_DB: honeycomb
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./data
        target: /var/lib/postgresql

  redis:
    image: redis:5.0.2
    restart: always

  honeycomb-service:
    build:
      context: ./
      dockerfile: build/local/Dockerfile
    depends_on:
      - minio
      - postgres
    environment:
      NODE_ENV: docker-compose
      ENV: local
      PGPASSWORD: iamaninsecurepassword
      PGUSER: honeycomb_user
      PGDATABASE: honeycomb
      PGHOST: postgres
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY: myaccesskey
      AWS_SECRET_KEY: mysecret
      S3_MINIO: "true"
      BEEHIVE_ENABLE_EVENTS: "no"
      # PROTON_PACK_STREAM_URI: http://proton-pack-service:5000/streams/honeycomb
    ports:
      - 4000:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
      - node-modules:/app/node_modules

volumes:
  node-modules:
