databaseChangeLog:
  - changeSet:
      id: environments-table
      author: pdecoursey
      context: live
      changes:
        - createTable:
            schemaName: honeycomb
            tableName: environments
            columns:
              - column:
                  name: environment_id
                  type: UUID
                  defaultValueComputed: uuid_generate_v4()
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(96)
              - column:
                  name: description
                  type: varchar(96)
              - column:
                  name: location
                  type: varchar(128)
              - column:
                  name: created
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
  - changeSet:
      id: coordinate-space-table
      author: pdecoursey
      context: live
      changes:
        - createTable:
            schemaName: honeycomb
            tableName: coordinatespaces
            columns:
              - column:
                  name: space_id
                  type: UUID
                  defaultValueComputed: uuid_generate_v4()
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(96)
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: start
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: end
                  type: TIMESTAMP
                  constraints:
                    nullable: true
