
---
apiVersion: batch/v1
kind: Job
metadata:
  name: honeycomb-migrate-v2021-03-31-19-03-02
  namespace: honeycomb
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: wildflowerschools/honeycomb-migrate:v2021-03-31-19-03-02
        envFrom:
          - secretRef:
              name: honeycomb-db-secret
      restartPolicy: OnFailure
  backoffLimit: 4
